In [1]:
import pandas as pd
import numpy as np
import datetime
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_excel('book1.xlsx',sheet_name='data')

In [3]:
data.head()

,PolicyNumber,Status,IssueYear,Date of Issue,Status Year,Status Date,Duration,FaceAmt
0,P2331392013,DH,2009,2009-09-02,2016,2016-01-07,8,1299969
1,R1035102007,LA,2015,2015-01-17,2016,2016-10-16,2,1414337
2,R1011882005,IF,2016,2016-01-22,2020,2020-12-31,5,546657

In [4]:
def create_data(PolicyNumber,dos,doe):
    global data_mart
    doe1 =doe
    dos1 = dos
    check = 0

    while dos < doe1:
        data_store = pd.DataFrame()
        if dos.year == 2015 and check == 0:
            temp = dos
            dos = datetime.datetime(2015,1,1)
            doe = temp
            check = 1
        elif dos.day == 1 and dos.month == 1:
            doe = dos1.replace(day = dos1.day,month = dos1.month,year=dos.year+1)
        else:
            doe = dos.replace(day=1,month=1,year=dos.year+1)
        if dos.year == doe1.year and dos.year != 2015:
            doe = doe1
        data_store['PolicyNumber'] = [PolicyNumber]
        data_store['COV PHASE'] = 1
        data_store['CLNDR YR'] = dos.year
        data_store['DRTN STR DT'] = dos
        data_store['DRTN END DT'] = doe
        data_mart = data_mart.append(data_store)
        dos = doe
        
    return "Complete"

In [5]:
data_mart = pd.DataFrame()

data['DOI'] = data['Date of Issue'].mask(data['Date of Issue'].dt.year < 2015,
                                           data['Date of Issue'] + pd.offsets.DateOffset(year=2015))

data['Status'] = data.apply(lambda x : create_data(x['PolicyNumber'],x['DOI'],x['Status Date']),axis=1)

In [6]:
data_mart

  PolicyNumber  COV PHASE  CLNDR YR DRTN STR DT DRTN END DT
0  P2331392013          1      2015  2015-01-01  2015-09-02
0  P2331392013          1      2015  2015-09-02  2016-01-01
0  P2331392013          1      2016  2016-01-01  2016-01-07
0  R1035102007          1      2015  2015-01-01  2015-01-17
0  R1035102007          1      2015  2015-01-17  2016-01-01
0  R1035102007          1      2016  2016-01-01  2016-10-16
0  R1011882005          1      2016  2016-01-22  2017-01-01
0  R1011882005          1      2017  2017-01-01  2018-01-22
0  R1011882005          1      2018  2018-01-22  2019-01-01
0  R1011882005          1      2019  2019-01-01  2020-01-22
0  R1011882005          1      2020  2020-01-22  2020-12-31